In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
df=pd.read_csv("../input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv")

**Text Preprocessing Steps**

In [4]:
import re
import nltk

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 10000):
  review = re.sub('[^a-zA-Z]', ' ', df['review'][i])
  review = re.sub('<.*?', ' ', df['review'][i])
  review = review.lower()
  review = review.split()
  ps = PorterStemmer()
  all_stopwords = stopwords.words('english')
  all_stopwords.remove('not')
  review = [ps.stem(word) for word in review if not word in set(all_stopwords)]
  review = ' '.join(review)
  corpus.append(review)

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()
y=df.iloc[:,-1].values[0:10000]
print(x,y)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] ['positive' 'positive' 'positive' ... 'negative' 'negative' 'positive']


In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [9]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
c1=GaussianNB()
c2=MultinomialNB()
c3=BernoulliNB()
c1.fit(x_train,y_train)
c2.fit(x_train,y_train)
c3.fit(x_train,y_train)
    


BernoulliNB()

In [10]:
y1=c1.predict(x_test)
y2=c2.predict(x_test)
y3=c3.predict(x_test)

In [11]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm1 = confusion_matrix(y_test, y1)
cm2 = confusion_matrix(y_test, y2)
cm3 = confusion_matrix(y_test, y3)
print(accuracy_score(y_test, y1))
print(accuracy_score(y_test, y2))
print(accuracy_score(y_test, y3))

0.621
0.8355
0.8495
